# This is a basic workflow that is manually triggered

name: Check Pull Requests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install
      run: npm install
      working-directory: webapp
    - name: Run Linter
      run: npm run lint
      working-directory: webapp
    - name: Run Tests
      run: npm run test:unit
      working-directory: webapp
      env:
        CI: true
